development:
  bucket_name: tbbdev
  access_key_id: AKIAJQPNQOXW46LVCXUA
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
    
test:
  bucket_name: test_bucket
  access_key_id: 
  secret_access_key: 
  max_file_size: 10485760
  
production:
  bucket_name: production_bucket
  access_key_id: 
  secret_access_key: 
  max_file_size: 10485760
